name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sellamiwael/project-online-shop:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            sudo docker pull sellamiwael/project-online-shop:latest
            
            # Stop and remove old container if exists
            if [ "$(sudo docker ps -aq -f name=project)" ]; then
              sudo docker stop project
              sudo docker rm project
            fi
            
            # Run a new container
            sudo docker run -d -p 80:80 --name project sellamiwael/project-online-shop:latest