name: Build, Push, and Auto Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-online-shop:latest

    - name: Deploy and restart container on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Pulling latest image..."
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-online-shop:latest

          echo "Stopping old container if exists..."
          sudo docker stop project || true

          echo "Removing old container..."
          sudo docker rm project || true

          echo "Starting new container..."
          sudo docker run -d -p 80:80 --name project ${{ secrets.DOCKERHUB_USERNAME }}/project-online-shop:latest

          echo "Deployment completed successfully."